name: jotti-dev

services:
  postgres:
    image: postgres:17
    container_name: jotti-postgres-dev
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: jotti
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d jotti"]
      interval: 5s
      timeout: 3s
      retries: 10

  migrate:
    build:
      context: ./database/migrate
      dockerfile: Dockerfile
    container_name: jotti-migrate-dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - app-network
    volumes:
      - ./database/migrations:/migrations
    depends_on:
      postgres:
        condition: service_healthy
    restart: "no"

  backend-dev:
    image: golang:1.25.4-alpine
    container_name: jotti-backend-dev
    working_dir: /src
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DBNAME: jotti
      JWT_SECRET: ${JWT_SECRET}
    command: sh -c "go mod download && go run ./main.go"
    volumes:
      - ./backend:/src
    networks:
      - app-network
    depends_on:
      migrate:
        condition: service_completed_successfully
      postgres:
        condition: service_healthy

  frontend-dev:
    image: node:24-alpine
    container_name: jotti-frontend-dev
    working_dir: /app
    environment:
      NODE_ENV: development
    command: sh -c "corepack enable && corepack prepare pnpm@latest --activate && rm -rf node_modules && CI=1 pnpm install --frozen-lockfile && pnpm dev --host 0.0.0.0"
    volumes:
      - ./frontend:/app
    networks:
      - app-network
    depends_on:
      backend-dev:
        condition: service_started

  reverse-proxy-dev:
    image: nginx:1.27-alpine
    container_name: jotti-reverse-proxy-dev
    ports:
      - "80:80"
    volumes:
      - ./reverse-proxy/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app-network
    depends_on:
      - frontend-dev
      - backend-dev

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
